# Generated by Django 5.2.7 on 2025-10-21 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailySystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_chats', models.IntegerField(default=0)),
                ('total_bot_handled', models.IntegerField(default=0)),
                ('total_agent_handled', models.IntegerField(default=0)),
                ('total_abandoned', models.IntegerField(default=0)),
                ('average_wait_time_seconds', models.IntegerField(default=0)),
                ('max_wait_time_seconds', models.IntegerField(default=0)),
                ('average_first_response_seconds', models.IntegerField(default=0)),
                ('total_ratings', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('peak_hour_chat_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HourlySystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('hour', models.IntegerField()),
                ('chats_started', models.IntegerField(default=0)),
                ('chats_completed', models.IntegerField(default=0)),
                ('chats_in_queue', models.IntegerField(default=0)),
                ('agents_online', models.IntegerField(default=0)),
                ('agents_available', models.IntegerField(default=0)),
                ('agents_busy', models.IntegerField(default=0)),
                ('average_wait_time_seconds', models.IntegerField(default=0)),
                ('average_response_time_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_h_timesta_66925f_idx'), models.Index(fields=['hour'], name='analytics_h_hour_de6d45_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSessionTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_tags', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tags', to='chat.chatsession')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_sessions', to='analytics.chattag')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('session', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='DailyAgentMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('total_chats', models.IntegerField(default=0)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_chat_duration_seconds', models.IntegerField(default=0)),
                ('average_chat_duration_seconds', models.IntegerField(default=0)),
                ('average_first_response_seconds', models.IntegerField(default=0)),
                ('average_response_time_seconds', models.IntegerField(default=0)),
                ('total_ratings_received', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('chats_transferred_out', models.IntegerField(default=0)),
                ('chats_transferred_in', models.IntegerField(default=0)),
                ('total_online_minutes', models.IntegerField(default=0)),
                ('total_break_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'agent'],
                'indexes': [models.Index(fields=['agent', 'date'], name='analytics_d_agent_i_e1b0c4_idx'), models.Index(fields=['date'], name='analytics_d_date_6b1437_idx')],
                'unique_together': {('agent', 'date')},
            },
        ),
    ]
