# Generated by Django 5.2.7 on 2025-10-21 21:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTranscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('messages_data', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('total_messages', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('chat_started_at', models.DateTimeField()),
                ('chat_ended_at', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-chat_ended_at'],
                'indexes': [models.Index(fields=['session_id'], name='chat_chattr_session_6d4b8b_idx'), models.Index(fields=['customer_email'], name='chat_chattr_custome_53b9a8_idx'), models.Index(fields=['chat_started_at'], name='chat_chattr_chat_st_2457c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_chats', models.IntegerField(default=0)),
                ('last_chat_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Customer Info',
                'ordering': ['-last_chat_date'],
                'indexes': [models.Index(fields=['email'], name='chat_custom_email_9b8876_idx'), models.Index(fields=['last_chat_date'], name='chat_custom_last_ch_80e48c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('bot', 'Bot Handling'), ('waiting', 'Waiting for Agent'), ('assigned', 'Assigned to Agent'), ('active', 'Active with Agent'), ('on_hold', 'On Hold'), ('abandoned', 'Abandoned'), ('closed', 'Closed')], db_index=True, default='bot', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer_url', models.URLField(blank=True, null=True)),
                ('browser_info', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resume_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('resume_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_abandoned', models.BooleanField(default=False)),
                ('is_resumed', models.BooleanField(default=False)),
                ('requires_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('wait_time_seconds', models.IntegerField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='chat.customerinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('agent', 'Agent'), ('system', 'System')], db_index=True, max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('delivery_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('closing', 'Closing'), ('common_issue', 'Common Issue'), ('escalation', 'Escalation'), ('hold', 'Hold Message'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('message', models.TextField()),
                ('shortcut', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_global', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category', 'is_global'], name='chat_canned_categor_a64cfe_idx'), models.Index(fields=['shortcut'], name='chat_canned_shortcu_59d9d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('response_time_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('helpfulness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'rating'], name='chat_chatra_agent_i_2bd19d_idx'), models.Index(fields=['created_at'], name='chat_chatra_created_5dc121_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('queue_position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('entered_queue_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('wait_time_seconds', models.IntegerField(default=0)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-priority', 'entered_queue_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'entered_queue_at'], name='chat_chatqu_status_0108b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_notes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chat_chatno_session_daf6c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('research', 'Need to Research'), ('escalation', 'Escalating to Supervisor'), ('technical', 'Technical Issue'), ('customer_request', 'Customer Requested Hold'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('hold_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_chats', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='chat.chatsession')),
            ],
            options={
                'ordering': ['-held_at'],
                'indexes': [models.Index(fields=['session', 'held_at'], name='chat_chatho_session_b24daa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('from_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='chat.chatsession')),
                ('to_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transferred_at'],
                'indexes': [models.Index(fields=['session', 'transferred_at'], name='chat_chattr_session_e041d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status', 'created_at'], name='chat_chatse_status_8e9421_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['assigned_agent', 'status'], name='chat_chatse_assigne_ef4d35_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer_email'], name='chat_chatse_custome_c6dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['is_abandoned', 'status'], name='chat_chatse_is_aban_597301_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['resume_token'], name='chat_chatse_resume__c2a80c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'created_at'], name='chat_messag_session_4940cf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'created_at'], name='chat_messag_sender__87817a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'sender_type'], name='chat_messag_is_read_0d2260_idx'),
        ),
    ]
